"""Added Fields to user Model

Revision ID: 8689dc9a0c74
Revises: a1889ed4109d
Create Date: 2023-05-09 01:05:47.611377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8689dc9a0c74'
down_revision = 'a1889ed4109d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userName', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('password', sa.LargeBinary(length=60), nullable=False))
        batch_op.create_unique_constraint(None, ['userName'])
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('password')
        batch_op.drop_column('email')
        batch_op.drop_column('userName')

    # ### end Alembic commands ###
